version: 0.2
phases:
  install:
    commands:
      - curl -qL -o packer.zip https://releases.hashicorp.com/packer/1.8.1/packer_1.8.1_linux_amd64.zip
      - unzip packer.zip
  build:
    commands:
      - ./packer init .
      - ./packer validate aws-ubuntu.pkr.hcl
      - ./packer build aws-ubuntu.pkr.hcl

      